apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterRole.yaml
- clusterRoleBinding.yaml
- configuration.yaml
- deployment.yaml
- service.yaml
- serviceAccount.yaml
- serviceMonitor.yaml
