apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    app.kubernetes.io/name: kubelet
    app.kubernetes.io/part-of: kube-prometheus
  name: kubelet-probes
  namespace: monitoring
spec:
  authorization:
    credentials:
      key: token
      name: prometheus-k8s-token
    type: Bearer
  honorLabels: true
  kubernetesSDConfigs:
  - role: Node
  metricRelabelings:
  - action: drop
    regex: container_(network_tcp_usage_total|network_udp_usage_total|tasks_state|cpu_load_average_10s)
    sourceLabels:
    - __name__
  - action: drop
    regex: (container_spec_.*|container_file_descriptors|container_sockets|container_threads_max|container_threads|container_start_time_seconds|container_last_seen);;
    sourceLabels:
    - __name__
    - pod
    - namespace
  - action: drop
    regex: (container_blkio_device_usage_total);.+
    sourceLabels:
    - __name__
    - container
  metricsPath: /metrics/probes
  relabelings:
  - action: replace
    sourceLabels:
    - __metrics_path__
    targetLabel: metrics_path
  - action: replace
    replacement: kube-system
    targetLabel: namespace
  - action: replace
    sourceLabels:
    - __meta_kubernetes_node_name
    targetLabel: node
  - replacement: kubelet
    targetLabel: job
  scheme: HTTPS
  scrapeInterval: 30s
  tlsConfig:
    insecureSkipVerify: true
