apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiService.yaml
- clusterRole.yaml
- clusterRoleAggregatedMetricsReader.yaml
- clusterRoleBinding.yaml
- clusterRoleBindingDelegator.yaml
- clusterRoleServerResources.yaml
- configMap.yaml
- deployment.yaml
- roleBindingAuthReader.yaml
- service.yaml
- serviceAccount.yaml
- serviceMonitor.yaml
