global:
  resolve_timeout: "5m"
inhibit_rules:
- equal:
  - "namespace"
  - "alertname"
  source_match:
    severity: "critical"
  target_match_re:
    severity: "warning|info"
- equal:
  - "namespace"
  - "alertname"
  source_match:
    severity: "warning"
  target_match_re:
    severity: "info"
receivers:
- name: "Default"
- name: "Watchdog"
- name: "Critical"
route:
  group_by:
  - "namespace"
  group_interval: "5m"
  group_wait: "30s"
  receiver: "Default"
  repeat_interval: "12h"
  routes:
  - match:
      alertname: "Watchdog"
    receiver: "Watchdog"
  - match:
      severity: "critical"
    receiver: "Critical"