apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-alertmanager

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-alertmanager
subjects:
- kind: ServiceAccount
  name: prometheus-alertmanager
  namespace: monitoring